server:
  port: 9090
  context-path: /AngularBoot

---
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect